### ISSUE TITLE
clarification of process model options

### ISSUE THREAD

**Issue by jakeberv** [pbastide/PhylogeneticEM#26]
Hi Paul,
I am still working with PhylogeneticEM, and I was hoping you could further clarify the process model options. 

The documentation notes:
process	
The model used for the fit. One of "BM" (for a full BM model, univariate or multivariate); "OU" (for an OU with independent traits, univariate or multivariate); or "scOU" (for a "scalar OU" model, see details).

When the input data are multivariate and 'BM' is selected, does this mean a full mvBM model is fit, where the full VCV can change at shift points? 

It seems this is not the case for when 'OU' is selected, as the 'independent' option indicates:
independent | Are the trait assumed to be independent from one another? Default to FALSE. OU in a multivariate setting only works if TRUE.

I read this as indicating that a full shifting mvOU model is not fit (hence the existence of scOU, which makes sense)-- but what is the behavior for mvBM/BM ? In the univariate case I assume the shifts are in the BM variance, but in the multivariate case, are the shifts allowed in variances and covariances among input traits (eg full mvBM like in mvMORPH)?

Cheers, and thanks for your attention to my prior questions as well.
Jake Berv

**Comment by pbastide** [comment]
Dear Jake,

Sorry, the documentation is indeed unclear. To answer your question, only the mean parameter (BM) or optimal parameter (OU) are allowed to change. All other parameters, including the rate variance matrix, are the same on the whole tree, i.e., do not change when the regime changes. Hence:

* The "BM" model with multivariate data is a multivariate BM, with a full rate variance matrix, shared on the whole tree, and a different expectations for each regime. All the expectation values for all the traits are forced to change when there is a regime shift.
* The "OU" model for multivariate data can only be the "independent" OU : all the traits are independent from one another (same model as in the "l1OU" package). Each trait has its own parameters. The selection strength and variance parameters are the same on the whole tree. The optimal parameters change at each shift on the tree. All the optimal values are forced to change when there is a regime shift.
* The "scOU" model for multivariate data is the "scalar OU" (see associated paper for more details). All the traits share the same selection strength parameter, but traits are not independent because we estimate a full variance covariance matrix between traits. Both parameters are the same on the whole tree. The optimal parameters change at each shift on the tree. All the optimal values are forced to change when there is a regime shift.

I hope this makes sense. Does it answer your questions ?

Thank you for your interest in PhyloEM, and for your feedback !

Kind regards,
Paul

**Comment by jakeberv** [comment]
I think so, thank you!
